---
format:
    html: 
        code-fold: false
    pdf:
        papersize: letter
        number-sections: false
        colorlinks: true
        highlight-style: github
        sansfont: Latin Modern Roman
editor: visual
---

## Daily Log

### Day 0: 5/10

This morning, I arrived to the ship after a very early flight. After spending the majority of the morning completing paperwork with the Captain, I spent the early afternoon meeting the engineers and getting a tour of the engine room. The M/V ARC Independence burns a heavy fuel distillate called very low sulfur fuel oil (VLSFO) and, as such, it requires steam heating to reduce the viscosity of the fuel and improve atomization and flow. While there are larger steam heaters, there are steam lines that wrap around the fuel oil lines to the main engine and one of these lines was leaking causing steam condensate to drip below the line onto the deck. I assisted the engineers in performing quick temporary repairs on the line, including using pipe clamps to reduce the pressure of steam into the line and thus reducing the amount of steam that was allowed to leak out. Next, I followed the Third Assistant Engineer around as he started to perform some pre-departure checks given that the vessel was slated to leave tomorrow.

### Day 1: 5/11

The morning's work involved exercising the at-sea spares for the main engine and ship service diesel generator exhaust valves. According to the First Engineer, this maintenance is typical prior to an Atlantic crossing. After threading in a service air connection to the side of the valve body and using the chain hoist to lift the assembly, the exhaust valves were allowed to move about their full length of travel and lubricated with Never-Seez. After the valves were completed. I assisted the Third in troubleshooting some non-functional deck lighting which included replacing light bulbs and chasing bad grounds.

### Day 2: 5/12

Today's work began by shadowing the oiler on her engine room round. This round was much shorter than the TSSOM oiler round as most of the items recorded were to be measured on the computer. There were only 4 manual tank soundings. Afterwards, I assisted the 3rd Engineer on continuing the LED fog light conversion project mentioned for the previous day. This involved removing the ballast for the previous light and then rewiring the leads directly. Ultimately, I was taken away from this project to perform an inspection on the secondary of the step-down transformer (440v to 220v) for the accommodation space and the upper car deck lighting. In this process, I learned that one cannot run two transformers in parallel because the secondaries act like two distinct sources. This was not intuitive to me. As such, it was necessary to de-energize the running starboard-side transformer before energizing the port-side transformer which meant a momentary blackout. After that, I returned to the LED fog light conversion project where I was responsible for milling lots into the brackets for the new lights. Finally, my day concluded with a bridge steering gear test as we were expected to go underway at 0100 (allegedly).

### Day 3: 5/13

Today, the M/V Arc Independence finally got underway. At 0800, I assumed the maneuvering watch with the Third Engineer. It involved mostly walking around the engine room, looking for leaks and checking the important temperatures and pressures. It also provided an opportunity to get familiar with the Kongsberg system. In the afternoon, it was back to maintenance. This began with the transformer that we had worked on yesterday, which was re-energized successfully with no major complications. With that being said, the transformer did create a small ground. I learned that this is due to the accumulation of moisture within the transformer. This is why it is very important to leave the transformer powered on the primary end even if the secondary is disconnected. This configuration will allow the energy stored within the field to heat up the copper windings and drive out moisture. After this, we made our way to the bow thruster compartment to take measurements on a motor that had an improperly-sized coupling installed on it (PICTURE).

Finally, the side vehicle bay loading door is not regularly used and the ship's crew is in the process of phasing it out due to leaking hydraulic components connected to the door. As such, I helped the first engineer remove two hydraulic cylinders from the door one to be used as a spare and the other to be rebuilt.