---
format:
    html: 
        code-fold: false
    pdf:
        papersize: letter
        number-sections: false
        colorlinks: true
        highlight-style: github
        sansfont: Latin Modern Roman

---

# Part 6 Steering Gear (As Applicable) {.unnumbered}

1.  List and describe the manufacturer and type of steering gear/system used on the ship.

Our steering gear was a Porsgrun AS electro-hydraulic steering gear and was rotary-vane type.

2.  List and describe the important points which require careful checking when inspecting and servicing the steering gear/system.

Important parts for inspection on the steering gear system include the hydraulic system, oil, rudder, feedback linkages and the operation of steering gear modes. The hydraulic system should be inspected for leaks and vibration from the motor. The oil should be checked for condition, including debris and contamination. The rudder should be inspected for integrity. At one point in my trip, a 55-mm crack was identified in the rudder stock and had to be repaired by underwater welders. The feedback linkages should also be checked, specifically those which tell the rudder angle indicator what position it is in. If these get lose, the control system would fail and no one would know the position of the rudder. Finally, all of the steering gear modes should be tested for functionality, including the autopilot, hand steering at all stations, followup and non-follow up.

3.  What are the USCG regulations on testing steering gear prior to departure from port? List the steps necessary for starting and testing the steering gear before leaving port.

Coast Guard regulations concerning testing the steering gear prior to leaving port are described under 33 CFR 164.25. The following must be tested at most 12 hours before departure from port: all steering gear control systems (follow-up, non-follow-up), all steering locations on the bridge, the rudder angle indicator, all power failure alarms on the control system and steering gear, moving the rudder the full range of motion for the gear. Prior to departure from port, our routine for testing the steering gear would include a call from the bridge to the steering gear room. Before receiving this call, we would have already checked for hydraulic fluid leaks and the level on the steering gear tank. We would begin by taking control of the steering gear on location and move the gear the full range of motion both port and starboard. We would then give the bridge control and they would do the same as we monitored for issues with the gear and position indicator. We would perform this test for both motors, one at a time, checking pressures along the way.

4.	What are the sources of power for the steering gear/system?

The steering gear's two electro-hydraulic motors were powered by the main electrical bus normally and the port pump was powered by the emergency generator upon loss of power to the main bus. 

5.	List and describe how the steering gear/system is controlled from the bridge, as well as from all alternate stations, including what modes of steering control are available and how the steering modes are shifted.

The steering gear system is controlled electronically from the bridge from any one of three stations. Steering could be controlled from the center control console or from either of the two bridge wings. There are three modes of steering control: autopilot, follow-up and non-follow-up. The autopilot is activated by pushing any of the buttons on the Furuno FAP-2000 as necessary for the maneuvering action to be taken. For example, to start the autopilot, the "go to waypoint" button can be pushed, then the main or backup autopilot buttons on the rudder control console and the autopilot will be engaged drawing data from the ECDIS. Steering modes can be shifted on the same rudder control console in addition to steering control location via separate buttons. NFU can be enabled by pressing the NFU button on the rudder control console, then turning the rudder with the mini wheel. Instead of controlling the follow up position of the rudder, the mini wheel will control how quickly the rudder is moving and in what direction. To send control to one of the bridge wings, the port or starboard wing button is pushed on this same console.

There are also some local control methods from the steering gear room. These methods are emergency non-follow-up modes and can cut out any issues that might be happening with the control system on the bridge. None of these methods require interaction from the bridge to enable. First, both pumps must be switched to local control mode. If one pump is still set to remote, the bridge controls can fight the local control. With the pump started, the port and starboard buttons on the pump control panel can be used to turn the rudder either direction. There are non-follow-up buttons located on both consoles for each pumps.

Finally, the most rudimentary method for controlling the steering gear system is the manual mode. With the desired pump started and in local, the variable frequency control for that pump should be switched off, meaning the pump is either on or off and will not be ramped up or down. Next, the levers on the directional control valve for either pump can be actuated either port or starboard with one hand. The other hand is used to hold open the pressure release lever as neither directional control lever can be actuated without it in the open position. 

6.	What type of pump is used to move the steering gear ram?  Describe the operation. 

The steering gear pump is a positive displacement rotary screw type pump and is controlled by a variable frequency drive (VFD). The pump draws oil from a hydraulic reservoir within the steering gear system. The oil is sent through a directional control valve which determines which side of the steering gear vanes the oil is sent to and hence the direction of rotation of the of the ram.

7.	List and describe how hydraulic fluid flows from the pump to move the rudder in the desired direction, and what happens when the rudder arrives at the ordered position.

Hydraulic fluid begins at the power unit driving the rudder. The fluid is pressurized up until the directional control valve which normally does not allow the flow of fluid through the valve. When the rudder receives a command to go to a specific position, the PLCs determine the direction that the rudder needs to move, either clockwise or counterclockwise, given the current position of the rudder. The directional control valve then either permits fluid to flow through the two inlet and outlet passages of the valve directly, or crosses fluid flow over to inverse the direction of rotation as appropriate. The fluid then flows to one side of the rudder vane and from the other side, causing the pressure of the fluid to push the rudder vane and change the angle of the rudder. The flow out of the chamber is permitted by the bypass valves (BP1 and BP2) which bypass the discharged fluid back to the sump of the power unit. There are two power pack systems which drive the port and starboard sides of the rudder hydraulic chambers respectively. These two independent systems can be crossed over by the cross connection valve block (CC1) which allows the port pump to drive the starboard chamber and vice versa. Or, the systems can be completely isolated from one another by a switch on the valve block in the event of a leak or some other issue. When the rudder arrives in the desired position, directional control valve blocks and the safety bypass valves are all closed. Hydraulic fluid is locked and pressurized in the chamber of the rudder, preventing it from moving due to currents or other movements of the ship. 

8.	Explain how the steering gear/system answers a rudder signal from the bridge correctly without overcompensating.

In the follow up mode of the steering gear, the rudder's position is continuously monitored by a potentiometer connected to the rudder by a mechanical linkage. The potentiometer is calibrated to know the angle of the rudder at any given time. As such, one the rudder is sent an order from the bridge, say 20° port, the directional control valves are sent a signal to turn to that direction and the rudder begins to turn in that direction. As the rudder is approaching the new set angle, the angle is measured on the potentiometer and the turn rate is reduced to check the rudder swing to ensure that the rudder does not overcompensate.

9.	What is used on the steering system for rudder stops? Explain their operation.

The steering gear system effectively had a combination of mechanical rudder stops and hydraulic cushions. There were adjustable stop bolts with blocks attached on top of the steering gear housing which could be set to specific angles to stop the rotor from passing outside of the safe ranges. Additionally, the flow constriction of the blocks effectively creates a hydraulic cushioning effect through the actuator to soften the rudder motion near these mechanical end stops.

10.	Explain the redundancy systems in your steering gear system and how they operate.

There are major redundancy systems in the steering gear system. These include the various modes of operation, the independent chambers of the steering gear actuator, multiple motors and power systems. The system had a lot of redundancy with its different modes of operation. Since the system could be controlled in multiple different ways, locally, from the bridge, autopilot and follow-up and non-follow up modes, there were many different ways to control the steering gear which could cut out any issues that were encountered in its operation. Additionally, the hydraulic ram had two different chambers. They were generally connected but could be isolated in the event of a leak. There were also two separate hydraulic pumps and motors which could each drive the steering gear on their own (or together for more speed). Additionally, there were different means of providing electrical power to the steering gear, from the main bus or from the emergency bus in case that main power is lost.

11.	Who maintains the steering gear/system on your ship? How often is it inspected?

The steering gear is maintained by the chief and first engineers as it was a critical system. Sometimes simple tasks such as greasing were delegated to the third engineer, but again this was largely under the perview of the senior engineers. The system was inspected by multiple engineers throughout the day. It received the most attention at the beginning of the day when all of the engineers and oilers did their daily rounds.