---
format:
    html: 
        code-fold: false
    pdf:
        papersize: letter
        number-sections: false
        colorlinks: true
        highlight-style: github
        sansfont: Latin Modern Roman
editor: visual
---

## Part 7 Refrigeration/Air-Conditioning (All Vessels)


1.	Write a detailed description of your ship’s refrigeration system and its operation, incorporating the following items:
•	compressors and operation, including unloading of compressor
•	condensers
•	metering device 
•	evaporators
•	safety equipment - cutouts and pressure relief devices
•	leak detection, fixed or manual?

Both of the ship refrigeration compressors had their condenser/receiver discharges tied directly together. After the condenser/receiver was a common filter drier that both compressors connected to. To switch over and start the opposite compressor, first close off the running condenser's discharge which will collect all of that compressor's refrigerant inside of the condenser. Once the low pressure cut out activates for that compressor, close off the inlet for that condenser. Now the other compressor can be started up and the running one taken offline.

After the refrigerant is cooled and condensed into a liquid in the LT water-cooled condensers, the suction refrigerant returning to the compressors is heated up by the liquid discharge refrigerant leaving the compressor skid. This is to ensure that the refrigerant returning to the compressors is completely a vapor and thus does not impinge on the compressor, causing pitting and damage. 

Next, the refrigerant is sent to a common line for each of the four refer boxes. There are a set of five valves for each refer box. First, liquid refrigerant travels through a stop valve, then a solenoid, TXV, then into the evaporator, check valve and then a stop valve. The solenoid is driven by an electronic thermometer which determines whether or not to turn on refrigerant flow to the unit. Once the unit drops below the set temperature, a timer runs to allow refrigerant to flow through the unit and cool down the space. The box temperatures are as follows: meat box, -20\degC; vegetable room, dairy room, and potato room, +4\degC. After the solenoid, the TXV continuously modulates itself based upon a sensing bulb on the opposite end of the heat exchanger, sensing refrigerant superheat to see how much to open or close.

The evaporators cause the refrigerant to flash into a vapor as heat is transferred from the refrigeration spaces into the liquid refrigerant that flows throughout the evaporators. These evaporators would periodically ice up and were on a timer for defrosting. When this happens, all solenoids are closed and an electric heating element runs for a set period of time to melt the ice. Once the evaporator temperature exceeds the set temperature of the defrosting mode, the heater will switch off. The defroster can be manually operated by setting the manual defrosting time switch, pressing the fan switch, then pressing the manual defrosting switch. This can be run as needed if the timer based defrosting does not achieve the desired effect. After the defrosting is complete, the run mode switch is put into the normal position.

There are two pressure cutouts on each compressor: KP1 and KP5. KP1 is the suction side low pressure cutout and regularly cuts out the compressor when all boxes are at their set temperatures so there is no refrigerant moving in the system. KP5 is the discharge side high pressure cutout and serves to protect the system and compressor from burning itself out or from pipes rupturing from an excessively high pressure. There are also two pressure relief valves between the two condensers which discharge to a vent line outside of the accommodation spaces above the refrigeration room. 

Leak detection is a manual process for this machine. The Swedish engineers before the vessel's reflag used a florescent dye tester to find leaks. However, both American chiefs on my vessel did not use this process and instead used an ultrasonic sniffer which "listened" for leaks, then used soap and water to pinpoint the specific location of any leaks. They also would use the presence of oil to identify additional locations of refrigerant leaks.

2.	Explain how temperature is controlled in the various ship service boxes.

We had four ship service boxes for the galley: the potato box, meat/fish box, dairy box and vegetable boxes. They all were fed refrigerant along the same header line. An electric thermostat was kept inside of each box and compared the measured temperature of the box to their respective setpoints. Then, when the temperature got too high, the thermostat opened the solenoid valve for that box. Refrigerant was then allowed to flow through the thermostatic expansion valve (TXV) for that box. The TXV was continually actuated by measuring superheat off of the outlet of the evaporator (which effectively was the temperature of the box) using a sensing bulb. As the gaseous medium inside of the sensing bulb heated up, pressure would increase in the capillary tube, exerting a force due to pressure on the top of the diaphragm for the TXV, opening the valve further and admitting more refrigerant to the evaporator within the service box, cooling the temperature of the space further. In theory, a TXV should fully seal and not allow anymore refrigerant through the valve once the temperature setpoint is met. However, in practice, there will often be a little bit of leak by. This is why the solenoids exist, to completely cut off flow to the system once the set temperature is reached. 

3.	Explain how cooling water flow through the ship’s refrigeration condensers is controlled.

Water flow through the ship's refrigeration condensers was controlled by orifice plates and gate valves. The gate valves did not offer significant control over the water flow through the refrigeration system, but did allow for isolation of the cooling system at those points. The major regulator for pressure were the orifice plates. The designers of the system knew the design pressure of the central fresh water system and stepped it down to safe levels for the refrigeration condenser cooling system using intentionally-sized orifice plates.

4.	List and describe any maintenance performed on the refrigeration system while you were aboard.

There was very little maintenance performed on the ship's refrigeration system while I was onboard. While I was onboard, the chief engineer replaced the compressor oil for the inboard refrigerant compressor and added more refrigerant to the outboard compressor. He suggested that he would just wait for the telltale alarm that the potato box temperature was getting too high to add refrigerant. He said that the potato box was always the first system to start increasing in temperature because it was the last system at the end of the refrigerant header. From there, he would connect up his refrigerant bottle with gauges to the compressor suction and discharge and add additional refrigerant per the manufacturer's guidelines. For the compressor oil, he would first pump down the system into the condenser/receiver and wait for the compressor to trip out on the low pressure cutout. From there, he would bleed off any pressure from the existing system refrigerant by venting it to atmosphere (which as I understand it is *not* de minimis release), then add the oil to the fill port of the compressor. He also explained that he would replace the filter/dryer once every other trip (60 days) by following the same procedure conducted for the oil change: first, pumping all of the refrigerant to the condenser/receiver, cutting out the compressor, isolating the filter dryer, then unscrewing it from the system.

5.	What type refrigerant is used in the ship service refrigeration system? What is the boiling point of the refrigerant at atmospheric pressure?

Our ship used R-407C which was a zeotropic mixture (400-series) of difluoromethane (R-32), pentafluoroethane (R-125), and tetrafluoroethane (R-134a). The zeotropic nature of the refrigerant means that the different component gases will fractionate, or separate out at different boiling points meaning that the refrigerant must be added as a liquid. The boiling point, however, is generally considered to be -43.8 \degC at atmospheric pressure despite the fractionation potential.

6.	What are the EPA certification requirements for technicians handling the various types of refrigerants used on your ship? Discuss briefly.

The two types of refrigerant being handled on my vessel were R407C and R134a. EPA certifications for handling refrigerants are based upon the capacity and type of system and not based upon the type of refrigerant being used. All systems on my vessel were greater than 10kg of charge and are high pressure systems. This means that they are governed by the EPA 608 type-2 license which pertains to systems that are over 5 pounds of charge and high pressure. However, myself and most of the engineers had EPA 608 universal, meaning they are authorized to handle type II systems in addition to type I (high pressure, lower than 5 lb of charge) and type-III systems (low pressure systems).

7.	List and describe how you would manually test for refrigeration leakage.

To test for refrigerant leakage on the relatively small systems on my ship, I would use a sniffer to first detect whether a leak was present. Sniffers are highly sensitive, so they would warn even if the leak was very small. However, if I had multiple units in close proximity, one might cause the other to trip positive. So, if a leak was suspected, I would put the sniffer on a lower sensitivity setting and move it near the pipes of the unit to try and find the general area where a leak is occurring. Then, to identify the leak, I would spray down the pipe with soapy water to see where bubbles formed. The size of the leak will determine the size of the bubbles created. I would specifically spray around fittings and areas where it looked like the pipe might rub and chafe. Perhaps the best way to identify a leak is not by looking for refrigerant, however. If a leak happens, the area around the leak may be especially oily because of the compressor lubricant that has leaked out with the refrigerant. While the refrigerant will vaporize when it enters the atmosphere, the compressor oil will not. Although my ship's refrigerant was not a chlorinated refrigerant, I could use the halide torch method to pinpoint the leak for any systems that did use chlorinated refrigerants so long as the combustion products associated with the refrigerant weren't toxic.

8.  List and describe your ship's air conditioning system and its operation.

My vessel contained mostly package air conditioning systems for various important locations throughout the ship. There were a total of 7 different package air conditioners: two on the bridge, two in the engine control room, one in the machine shop, one in the galley and one in the switchboard room. All of the package units were the same with the exception of the unit in the switchboard room which was much larger and had more redundancy (two compressors, for example). Operationally, these were fairly simple. They contained a switch for fan or air condition. In air condition mode, they would move heat from the air in the room too the central freshwater cooling system that was used to cool the air conditioner's evaporator, cooling the space. In heating mode, a simple resistive electric heater element was used to heat the air.

The accommodation air conditioning system comprised four reciprocating compressors, two each for the forward and after section of the accommodation space. Generally, one compressor for each section of the house would be run at any given time, however, they could be run in parallel in hot climates such as when we were in the Gulf of America or the chief engineer wanted to be less hungover the following day after a port call. After the compressor compresses the R407C vapor, the vapor travels into the condenser for that section where it is cooled by the central fresh water on the other side of the shell and tube heat exchanger and it condenses into a high pressure liquid. After that, the slightly warm high pressure refrigerant travels two one of two air handlers also in the refer room. Inside of the air handler is a large radiator-style heat exchanger in which the high pressure liquid refrigerant is vaporized by a significant drop in pressure after the metering device in the radiator. This causes the refrigerant to absorb a significant amount of heat from the heat exchanger, which causes the air in the air exchanger to transfer its heat and cool down. From this air handler, air is distributed throughout the accommodation spaces with the exception of the bridge, which is on its own HVAC circuit per the package air conditioners described above.

9.	List and describe the following for the AC compressors and include quantity, type, number of cylinders, bore, stroke, rpm, etc.

Our accommodation air conditioning plant had 4, 40HP Carlyle 6-cylinder semi-hermetic compressors with a 99 CFM displacement at 1,750 RPM. The bore was 2.688 inches and stroke was 2.874 inches. 

There were also several packaged air conditioning units with different hermetic compressors. Specific data for these compressors such as bore and stroke were not provided as it is not applicable to scroll-type compressors. All packaged air conditioners were manufactured by Namirei-Showa Korea.

The switchboard AC was a model USP15H with two JT236DATFYE scroll type compressors running at 3450 RPM and each drawing 5.5 kW (for a total of 11 kW). The engine control room and workshop ACs were USP8H units with cooling capacities of 24,000 kcal/hr with a single JT236DATFYE scroll type compressor. The engineer's changing room AC was a USP5H unit with a semi-hermetic scroll-type compressor with a cooling capacity of 15,000 kcal/hr. The compressor in this unit was a model JT150BK-YE with a speed of 3450 RPM and drawing 3.75 kW. The unit in the dry provision room (attached to the galley) was a USF5JA with a cooling capacity of 15,000 kcal/hr. The compressor for this unit was also a model JT150BK-YE with a speed of 3450 RPM and drawing 3.75 kW. The wheelhouse had two units: an FDIF200 and an FDIF400. Between these two units, the wheelhouse had a total cooling capacity of 30,000 kcal/hr. The compressors for both units were JT300DAFYE with a speed of 3450 RPM and power of 7.5 kW.

10.	List and describe any maintenance performed on the air conditioning system while you were aboard.  

Very minimal maintenance was performed on the air conditioning system while I was onboard. Most of the air conditioning units were self-contained package units which did not require much in the way of servicing. While I was onboard, I was assigned the task of the 6-month service, which included cleaning the internals of the system, filters, inspecting for corrosion and checking the belts. I had to replace two belts on the air conditioner air handler unit for the main switchboard room. 